### PR TITLE
Prevent duplicated path prefix elements in generated URLs take two

### PR DESCRIPTION
**Pull request by burnettk**
This builds on https://github.com/sartography/spiff-arena/pull/1349.

Regarding the test that failed when we did not use the config, the test itself had an unnecessary assumption that we needed to rely on config, but in fact flask's knowledge of the URL is sufficient and I think @mogul 's first idea was good. I have also updated the SPIFFWORKFLOW_BACKEND_URL to match what flask will use in unit tests. We might be able to remove further use of the SPIFFWORKFLOW_BACKEND_URL in a subsequent change. i think we only need it when we are not in the context of a request.

## Summary by CodeRabbit

- **Enhancements**
	- Improved URL generation and handling in OpenID authentication routes for better consistency and flexibility.
	- Dynamically set the backend base URL for local development environment setup to enhance flexibility.

### CODE REVIEW

**Comment by mogul** [comment]
From #1349:
> [...] and since request.host_url is sufficient, I think we should go with your first suggestion and avoid config where possible. i made that change over there.

and
>  i think we only need it when we are not in the context of a request.

That's what I was thinking when I read that rant about WSGI and `SCRIPT_NAME`: "Why require the `SPIFFWORKFLOW_BACKGROUND_URL` in the codebase at all?"... but I didn't want this change to spill outside of specifically what I was trying to fix, and I didn't know if you had other reasons for needing that variable and port number in the codebase. This is great to see, and I hope it means further elimination of code paths where things could be done inconsistently or break depending on operator/deployment config all over the codebase.

**Comment by mogul** [comment]
Now testing and I see two things: 

- The image/css/js elements are not being found when displaying the `login.html` template despite [that template using `url_for` consistently](https://github.com/sartography/spiff-arena/blob/GSA-TTS-fix-path-routing-in-generated-openid-urls/spiffworkflow-backend/src/spiffworkflow_backend/routes/openid_blueprint/templates/login.html).
- The protocol was lost during redirection, so the form was posted to `http://` instead of `https://`. So that needs to be retained and explicitly used somehow.

Looking at the rendered page, I see URLs like:
- `http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov//api/openid/static/login.css`
- `http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov//api/openid/static/logo_small.png`
- `http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov//api/openid/form_submit`

So in addition to the protocol not being retained, there's still a stray `/` getting injected in there. When I manually fixed both things in the URL for each of the static assets in Chrome's Inspector, the page looked correct. However, when I fixed the form URL and then submitted it, I got this result:

```json
{
  "error_code": "invalid_token",
  "message": "Login failed. Please try again",
  "status_code": 401
}
```

I'm pretty sure that's because of an http/https mismatch in the generated token. So I think we're almost there!

**Comment by mogul** [comment]
Oh, the extra slashes are explicitly there in the template:

```jinja
href="{{ host_url }}/{{ url_for('ROUTENAME', filename='FILENAME') }}"
                   ^^^
```

So removing those will fix the login page.

**Comment by burnettk** [comment]
committed a fix for the double forward slash. if `request.host_url` continues returning "http" instead of "https" for you, you could try `SPIFFWORKFLOW_BACKEND_USE_WERKZEUG_MIDDLEWARE_PROXY_FIX=true` in backend. will test on an internal deployed environment tomorrow to make sure it's acting like localhost.

**Comment by mogul** [comment]
The double-slash in the path is fixed, and the image on the login page loaded, but the http/https situation remains. The Chrome Inspector console laid the situation out pretty clearly:

- `Mixed Content: The page at 'https://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid/auth?state=REDACTED&response_type=code&client_id=spiffworkflow-backend&scope=openid%20profile%20email&redirect_uri=http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/v1.0/login_return' was loaded over HTTPS, but requested an insecure element 'http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid/static/logo_small.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html`
- `Mixed Content: The page at 'https://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid/auth?state=REDACTED&response_type=code&client_id=spiffworkflow-backend&scope=openid%20profile%20email&redirect_uri=http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/v1.0/login_return' was loaded over HTTPS, but requested an insecure stylesheet 'http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid/static/login.css'. This request has been blocked; the content must be served over HTTPS.`
- `Mixed Content: The page at 'https://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid/auth?state=REDACTED&response_type=code&client_id=spiffworkflow-backend&scope=openid%20profile%20email&redirect_uri=http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/v1.0/login_return' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid/form_submit'. This endpoint should be made available over a secure connection.`
- `Mixed Content: The page at 'https://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid/auth?state=REDACTED&response_type=code&client_id=spiffworkflow-backend&scope=openid%20profile%20email&redirect_uri=http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/v1.0/login_return' was loaded over HTTPS, but requested an insecure element 'http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid/static/logo_small.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html`
- `Mixed Content: The page at 'https://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid/auth?state=REDACTED&response_type=code&client_id=spiffworkflow-backend&scope=openid%20profile%20email&redirect_uri=http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/v1.0/login_return' was loaded over HTTPS, but requested an insecure stylesheet 'http://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid/static/login.css'. This request has been blocked; the content must be served over HTTPS.`

Adding `SPIFFWORKFLOW_BACKEND_USE_WERKZEUG_MIDDLEWARE_PROXY_FIX=true` fixes the protocol issue, thanks! However, I'm still not able to login. I get a 401 with 

```JSON
{
  "error_code": "invalid_login",
  "message": "Login failed. Please try again",
  "status_code": 401
}
```

In the logs I see:

```
TOKEN INVALID because ISS 'https://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/openid' does not match server url 'https://spiffworkflow-gibbon-mouthpiece.app.cloud.gov/api/openid'
```

**Comment by burnettk** [comment]
the "TOKEN INVALID because ISS [does not match]" error is hopefully resolved with the latest commit.

**Comment by burnettk** [comment]
this would be much harder without the perfect amount of debugging information in these comments, thank you.

**Comment by burnettk** [comment]
pushed another url_for 1 minute ago. tested locally with configs closer to target.

**Comment by mogul** [comment]
😎 🚀 
image

**Comment by burnettk** [comment]
fantastic, glad to see it working, and thanks for the code and debugging assistance throughout. will merge to main and you should show up on the new contributors list when we cut the next release.

**Pull request merged**
