### PR TITLE
Feature/process navigation

### PR DESCRIPTION
**Pull request by essweine**
This https://github.com/sartography/SpiffWorkflow/pull/273 needs to be merged before this.

### CODE REVIEW

**Review by jbirddog — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Comment by burnettk** [comment]
is this the sort of thing that should require elevated permissions, @essweine ? or, like, if you kicked off the process instance, then you should be able to send messages to these sorts of activities?

**Comment by essweine** [comment]
I think elevated permissions are probably a good idea -- you could potentially screw something up.  I would say they should be the same as for editing task data.

**Comment by essweine** [comment]
The frontend tests seem to be failing because of timeouts, problems with keycloak, etc.  I don't understand why the backend tests fail on reordering imports because nothing changes when I run it.

**Comment by burnettk** [comment]
please ignore the frontend tests for now. they are currently broken, and
we'll fix them when we have some time. re: imports, are you running
./bin/run_pyl from spiff-arena ?

**Comment by essweine** [comment]
I'm done with this, except for the pre commit script failing.  If I run the linting script it changes almost every file in the repo and then errors out.  If I run only orerdering imports, nothing changes.  It irritates me that stupid stuff like this causes problems, yet we have multi thousand line files with unused and commented out code..  So anyway, maybe somebody else can pull this and run the script locally; I'm officially giving up on it.

**Comment by burnettk** [comment]
sure, hammered `./bin/run_pyl` from spiff-arena and it made some minor changes to two files. you may or may not be happy to learn that we just split up the process_api_blueprint.py file into five or six files based on the "resource type" (process model, process group, task, etc). also, you should merge this before we get that branch into main. but yeah, there's garbage code, for sure. sonarcloud calls us out on commented out code, too. it would be nice to have more time to refactor and clean stuff up. all in all it's decent, though, i think.

**Pull request merged**
