### PR TITLE
update-spiffworkflow

### PR DESCRIPTION
**Pull request by jasquat**
NOTE: 
Includes data migration to version 5.
This updates the task state on multi instance tasks for new spiff.

## Summary by CodeRabbit

- **New Features**
  - Introduced migration logic for Version5, ensuring smoother transitions and updates for process instances.
  - Added a new complex BPMN workflow definition for testing multi-instance tasks.

- **Bug Fixes**
  - Improved task query functionality to enhance accuracy in task selection.

- **Tests**
  - Added new tests to verify the functionality of Version5 migrations.
  - Enhanced test logging for better debugging and validation.

- **Chores**
  - Updated internal mappings and added print statements for better traceability during task completion.

### CODE REVIEW

**Review by burnettk — APPROVED** [review]

**Comment by madhurrya** [comment]
@jasquat @burnettk can this affect old instances?

**Comment by burnettk** [comment]
@madhurrya potentially.

**Comment by madhurrya** [comment]
Are there any specific areas that can be affected with this update?

**Comment by burnettk** [comment]
it was mostly MI and loop task related.

**Pull request merged**
