### PR TITLE
Look for bad get_current_user scripts

### PR DESCRIPTION
**Pull request by burnettk**
also puts xml parsing in one place and makes it a little safer.
also uses ruff check to avoid deprecation of `ruff .`
deals with comment on #773 about using get_current_user breaking some instances.

## Summary by CodeRabbit

- **New Features**
	- Introduced a script to identify uses of `get_current_user()` in BPMN files, enhancing security and compliance checks.

- **Refactor**
	- Improved the autofix process by integrating `check` with `--fix` in the `Makefile` and `run_pyl` script for more comprehensive code quality checks.
	- Enhanced XML parsing security and efficiency in the process model testing service by updating method implementations for better file handling and parser configuration.

- **Chores**
	- Updated internal scripts and services for better performance and security compliance.

### CODE REVIEW

**Review by jbirddog — APPROVED** [review]

**Comment by madhurrya** [comment]
@burnettk is this deployed in dev.mod?

**Comment by burnettk** [comment]
there is nothing to deploy, since the script is run locally. if we want to know if there are bad scripts on a certain branch, i can check.

**Comment by madhurrya** [comment]
I am not clear KB. Doesn't these files related to this PR needs to be deployed in dev.mod if I need to check if this fixes the old instance issue I have mentioned in #773?

**Comment by burnettk** [comment]
@madhurrya there is no reasonable way to fix instances that were run with a process model that doesn't conform to these policies. ideally we fix process models so no new bad instances are created, flush out the bad instances until we feel we can manage the rest manually, and then deploy celery.

**Comment by burnettk** [comment]
we could theoretically write a script to figure out if any open process instances would be affected. it would be significantly harder to write than the existing script, and even more difficult on prod, where we don't have access.

**Comment by madhurrya** [comment]
If we update the existing models accordingly now, then we'll not get this issue with the old instances of those updated models right? Have we already updated those models or not yet? Have you already discussed this with @sashayar13 ?

**Comment by sashayar13** [comment]
I haven't updated all process models yet, was planning to do so during the week. But it will not solve the issue - there still will be old open instances in prod since people are doing the expense submission to the previously opened Travel and Purchase requests. We need to have a way to handle such old instances

**Comment by burnettk** [comment]
ok, first we need to fix the models in prod, and then i see a few options here:

1. note the time that we updated prod, maybe 30 apr 2024, or whenever that happens. wait a few weeks. do a query for instances created before 30 apr 2024. those instances are bad. if there are 3, talk to the the people who "own" the instances, mitigate the potential impact, and deploy celery. if there are 50, wait a few more weeks. eventually there are few enough instances that we can safely release celery without causing too much damage.
2. write a script that detects bad instances. this would take about 3 or 4 days. that way we could have a better idea about which of the 50 instances could actually be affected by the get_current_user issue. this is not the greatest type of work because part of it would only be applicable for this one issue, and then we'd throw it away.
3. try to really understand the nature of the process models that are affected and figure out a way to make old instances work by writing some sort of script. this is likely to be a 5 to 10 day task, most of the value of which wouldn't be carried forward (the learnings and code produced would only be applicable for this one issue, and then we'd throw it away), so i wouldn't recommend it.

**Comment by sashayar13** [comment]
@burnettk, we have already updated all process models affected by the change. These process models are in prod from 29.04

I can check how many open instances we have created before this date and let you know. Based on the number and nature we can see which option is acceptable

**Comment by sashayar13** [comment]
373 not completed process instances with the start date before 29.04.2024
Next step - analyse the nature of the process instances and plan the next steps accordingly

**Comment by madhurrya** [comment]
Since we are still testing and bug fixing things in Celery I assume it'll take atleast another month or so to reach it to Prod. By that time wouldn't most of those instances will be closed?
Still we'll have to take action for any instances that'll be open.

**Comment by sashayar13** [comment]
@madhurrya, may I ask you please to inform me a week prior to the change release date?

**Comment by madhurrya** [comment]
@sashayar13 I guess you mean before the Celery release. Yes sure will let you know.

**Pull request merged**
