### PR TITLE
Feature/generic webhook

### PR DESCRIPTION
**Pull request by jasquat**
test pr for webhook

test edit1

## Summary by CodeRabbit

- **New Features**
	- Updated the system to handle webhooks from external systems, including GitHub, with enhanced authentication and processing.
	- Introduced new configurations for webhook handling and GitHub authentication.
	- Added the ability to automatically create and run process instances based on webhook data.
	- Implemented a new process for sending and receiving messages within the workflow system.
- **Enhancements**
	- Streamlined the process creation and execution logic for better readability and maintainability.
	- Enhanced user-related operations with checks and system user creation for message processing.
- **Bug Fixes**
	- Removed unnecessary imports and functions to clean up the codebase.
- **Tests**
	- Added new tests for webhook handling and message sending functionalities.

### CODE REVIEW

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — COMMENTED** [review]
test comment

**Review by burnettk — CHANGES_REQUESTED** [review]
need changes test

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Comment by jasquat** [comment]
This testing is done.

**Comment by burnettk** [comment]
test comment

**Comment by burnettk** [comment]
testing

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Review by burnettk — APPROVED** [review]

**Pull request closed without merging**
