### PR TITLE
Numeric range field added (#799)

### PR DESCRIPTION
**Pull request by burnettk**
originally from: https://github.com/sartography/spiff-arena/pull/799

Implements #647.

Added a custom field to handle numeric ranges. The field checks for the first key in the properties of the schema and will add min and max to it when the values are put in.

## Summary by CodeRabbit

- **New Features**
  - Introduced a `NumericRangeField` component for inputting numeric ranges in forms.
  - Updated form validation to include custom checks for new field types.

- **Style**
  - Adjusted color values, margins, and padding across various CSS elements for improved visual presentation.
  - Enhanced styling for `rjsf` components, including font size, width, and color adjustments.

- **Documentation**
  - Added documentation for the new `NumericRangeField` feature, including usage examples and validation details.

- **Bug Fixes**
  - Temporarily disabled certain backend calls and form button disabling logic for smoother user experience.

### CODE REVIEW

**Comment by burnettk** [comment]
please run `npm run lint` in the spiffworkflow-frontend directory. you can normally run npm run lint:fix` to autofix some stuff, but i already did that and committed it to this branch.

**Comment by burnettk** [comment]
@Kayvon-Martinez can you supply a sample process model or otherwise describe or give examples of what the json schema and ui schema should look like? we were having some issues figuring out how to use it and it was giving us validation errors when submitting the form.

**Comment by burnettk** [comment]
@coderabbitai hey, can you write some documentation about how this feature works and how to use it (how to write json files and whatnot) in markdown format?

**Comment by burnettk** [comment]
@Kayvon-Martinez we made some updates. we made the auto-set min and max based on the other value (and switching min and max values) a little less magical. hopefully the result feels ok to you when you use it. because of that, we had to add validation logic, so that is now in place. and a few other things. please reach out if anything seems amiss or if you'd like to talk anything through; we are more than happy to do so. Please take a look at the coderabbit comments and update code if it seems worth updating and then click "Resolve conversation" when you are happy with those. we learned about `ui:field` from this change, and we'll probably update one of our ui:widgets to use this approach. thank you!

**Comment by Kayvon-Martinez** [comment]
I just tested it and I love the changes you made! Thank you! I have confirmed the merge. Thanks again!

**Pull request merged**
