### PR TITLE
tweak readme for testing PR approval

### PR DESCRIPTION
**Pull request by burnettk**
tweak readme for testing PR approval
feel free to either merge or close.

## Summary by CodeRabbit

- **Documentation**
	- Improved text formatting and structure for enhanced readability.
	- Updated setup and application running instructions.
	- Added clarifications for using Docker in local development.
	- Detailed information on available `make` targets.
	- Refined presentation of license information.

### CODE REVIEW

**Review by madhurrya — CHANGES_REQUESTED** [review]
Pls update these xxxx

**Review by madhurrya — DISMISSED** [review]
Approve

**Review by madhurrya — COMMENTED** [review]
aa

**Comment by jasquat** [comment]
Closing since this is no longer needed.

**Pull request closed without merging**
